### ISSUE TITLE
Support tags for queries

### ISSUE THREAD

**Issue by dssib** [sib-swiss/sparql-examples#20]
Features for compatibility with GRLC format: supporting the addition of tags to the queries?

**Comment by JervenBolleman** [comment]
Already there in part, schema:keyword see https://sib-swiss.github.io/sparql-examples/examples/neXtProt/NXQ_00301.rq for an example.

**Comment by dssib** [comment]
No, I think for now this is good, thank you for pointing it out! Just for later reference, I mention the corresponding formatted example here https://github.com/sib-swiss/sparql-examples/blob/master/examples/neXtProt/NXQ_00301.ttl#L17 . I'll also add a mention in the Readme.
