### ISSUE TITLE
MetaNetX example 11 does not work

### ISSUE THREAD

**Issue by dssib** [sib-swiss/sparql-examples#25]
Virtuoso 37000 Error SP031: SPARQL compiler: Variable ?reac is used in the result set outside aggregate and not mentioned in GROUP BY clause

Error happens when running query [11](https://github.com/sib-swiss/sparql-examples/blob/master/examples/MetaNetX/11.ttl).

**Comment by tarcisiotmf** [comment]
fixed by adding ?reac in the group by statement commit: 0d4c165ee389a29682612c0f0404beeaca358674
