### ISSUE TITLE
Add LIMITs wherever relevant

### ISSUE THREAD

**Issue by dssib** [sib-swiss/sparql-examples#26]
We should strive for the examples to be runnable in a reasonable time. In some cases it's straightforward to add LIMITs to the queries, we should at least add them in such cases. An example consists in Uniprot queries that query for the names of all proteins, e.g. [here](https://github.com/sib-swiss/sparql-examples/blob/master/examples/UniProt/uniprot_recomended_protein_full_name.ttl#L8).

**Comment by JervenBolleman** [comment]
This is done in         private static String addLimitToQuery(QueryParser parser, Value obj, QueryTypes qt,
